services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./src/grafana/provisioning:/etc/grafana/provisioning
      - ./src/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    networks:
      - monitor-net

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    volumes:
      - ./src/blackbox/config.yml:/etc/blackbox_exporter/config.yml
    networks:
      - monitor-net

volumes:
  grafana-storage:

networks:
  monitor-net:
    driver: bridge
