modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2", "HTTP/2.0"]  # Adicionar HTTP/2.0
      valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226]  # Accept 2xx status codes.
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      ip_protocol_fallback: true  # Adicionar fallback para IPv4
      preferred_ip_protocol: "ip4"  # Forçar uso de IPv4
