groups:
  - name: example
    rules:
      - alert: TargetDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Target {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  - name: blackbox
    rules:
      - record: job:blackbox_http:probe_success
        expr: probe_success{job="blackbox-http"}
