global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://example.com/
        - https://httpstat.us/200
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Adicionar uma regra de gravação para ver o status
rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

# Exemplo de query no Prometheus para testar o Blackbox Exporter
# Acesse http://localhost:9090 e execute a seguinte query:
# probe_success{job="blackbox-http"}
